version: "3.9"
services:
  pulsar:
    image: "apachepulsar/pulsar:2.8.0"
    entrypoint: bin/pulsar standalone
    environment:
      PULSAR_MEM: "-Xmx1024m -XX:MaxDirectMemorySize=1024m"
    volumes:
      - pulsar-data:/pulsar/data
    ports:
      - "6650:6650"
      - "8080:8080"
  influx:
    image: "influxdb:1.7.0"
    ports:
      - "8086:8086"
      - "2003:2003"
    volumes:
      - influx-data:/var/lib/influxdb
      - $PWD/config/influxdb.conf:/etc/influxdb/influxdb.conf
    environment:
      DOCKER_INFLUXDB_INIT_MODE: "setup"
      DOCKER_INFLUXDB_INIT_USERNAME: "admin"
      DOCKER_INFLUXDB_INIT_PASSWORD: "admin"
      DOCKER_INFLUXDB_INIT_ORG: "my-org"
      DOCKER_INFLUXDB_INIT_BUCKET: "my-bucket"
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "dap"
      INFLUXDB_GRAPHITE_0_DATABASE: "graphite"
      INFLUXDB_GRAPHITE_0_ENABLED: "true"
      INFLUXDB_GRAPHITE_0_BIND_ADDRESS: ":2003"
  grafana:
    image: "grafana/grafana:6.6.0"
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
volumes:
  pulsar-data:
  influx-data:
  grafana-data: